### PR TITLE
yaml plugin

### PR DESCRIPTION
**Pull request by vkosuri**
This PR address https://github.com/mbj4668/pyang/issues/291 issue, @mbj4668 @llhotka and @jean-christophe-manciot please let me know your comments or suggestions

### CODE REVIEW

**Comment by vkosuri** [comment]
It will produce output like this

``` Bash
(venv)dev@vkosuri-vm:~/pyang$ pyang -f yaml test/test_good/yt9.yang
- yt9:module
  a1: int32
    - con1:container
      a2: string
```

**Comment by vkosuri** [comment]
```yaml
---
openconfig-vlan: 
  vlans: 
    vlan: 
      - vlan-id:
        config: 
          vlan-id:
          name:
          status:
          tpid:
        state: 
          vlan-id:
          name:
          status:
          tpid:
        members: 
          member: 
```

**Comment by vkosuri** [comment]
@mbj4668 any comments/suggestions?

**Comment by vkosuri** [comment]
@mbj4668 any updates?

**Comment by mbj4668** [comment]
I don't understand how this is useful.  It merely prints the structure of a model w/o any additional info like type info etc.

**Comment by vkosuri** [comment]
@mbj4668 I have made changes based on @jean-christophe-manciot inputs,  @jean-christophe-manciot could you please provide more input why it useful, and what type information is required to print structure data.

**Comment by jean-christophe-manciot** [comment]
This conversion would be useful to be able to build data models in yaml based on their yang counterparts.
Doing the conversion manually is very cumbersome, considering the number of yang data models, their length and complex structure due to dependencies ("import"), not mentioning the fact that they are often updated and improved..

**Comment by skamithi** [comment]
agree with @jean-christophe-manciot . Helpful for Ansible users who want to use OpenConfig as a base data model for their automation because Ansible uses YAML as the  language for variables.

**Comment by babukt** [comment]
Hi,

Is this plugin in production? I'm looking to generate YAML format for RPC's as below so the user can able to fill respective fields to provide this as input to an API.

Tree:

+---x get-interface-information
    |  +---w input
    |  |  +---w interface-name?         string
    |  |  +---w level?                  enumeration
    |  |  +---w snmp-index?             union

YAML:

get-interface-information:
  input:
    interface-name: string
    level: enumeration
    snmp-index: union

**Comment by vkosuri** [comment]
Thanks, https://github.com/vkosuri/pyang-yaml-plugin feature work goes here

**Pull request closed without merging**
