### PR TITLE
Reset validation state before post-transform re-validation

### PR DESCRIPTION
**Pull request by wlupton**
These are the changes from the `mbj/transform-reset-env` branch (discussed in issue #437). They still seem to successfully avoid the 'imported module not used' warnings.

The changes below are the only differences from `master` (apart from adding the two new `internal_reset()` methods). I believe that the `module.i_is_validated = False` line was added more recently (to address #465) but I assume that it's correct to replace both it and the following line.

```
     # transform modules
     if len(xform_objs) > 0 and len(modules) > 0:
+        ctx.internal_reset()
         for xform_obj in xform_objs:
             try:
                 if not xform_obj.transform(ctx, modules):
                     for module in modules:
-                        module.i_is_validated = False
-                        statements.validate_module(ctx, module)
+                        module.internal_reset()
+                        ctx.add_parsed_module(module)
```

### CODE REVIEW

**Comment by wlupton** [comment]
(There are no new changes. I noticed that there were conflicts, so I rebased and pushed.)

**Comment by wlupton** [comment]
Oops. I should have looked more closely at the rebase conflicts. I'll fix the error.

**Comment by wlupton** [comment]
I've added the missing `Context.internal_reset()` but something seems to be wrong, e.g., see below.

```
lewa:test_transform% pyang -f tree a.yang 
module: a
  +--rw x
     +--rw y?   string
```

```
lewa:test_transform% pyang --plugindir . -t add-foo -f tree a.yang 
module: a
Traceback (most recent call last):
  File "/Users/william/Development/pyang/feature/bin/pyang", line 530, in <module>
    run()
  File "/Users/william/Development/pyang/feature/bin/pyang", line 499, in run
    emit_obj.emit(ctx, modules, fd)
  File "/Users/william/Development/pyang/feature/pyang/plugins/tree.py", line 85, in emit
    ctx.opts.tree_line_length, path)
  File "/Users/william/Development/pyang/feature/pyang/plugins/tree.py", line 158, in emit_tree
    prefix_with_modname=ctx.opts.modname_prefix)
  File "/Users/william/Development/pyang/feature/pyang/plugins/tree.py", line 322, in print_children
    width = get_width(0, i_children)
  File "/Users/william/Development/pyang/feature/pyang/plugins/tree.py", line 310, in get_width
    if ch.i_module.i_modulename == module.i_modulename:
AttributeError: i_modulename
```

**Comment by fredgan** [comment]
Hi @wlupton , I am looking at this issue. However, I don't understand why you add two `internal_reset`, especially removing all `i_` prefix properties. Because the `i_modulename` is removed, so it crash like what you refered to. Would you like to explain more to me to understand it? Thanks

**Comment by wlupton** [comment]
One resets the context, and the other resets a module (well... a statement and its sub-statements... but it's called on a module statement). The idea (I believe) is to reset all the internal state back to what it was at the beginning, so the validation after a transform will be a full validation.

**Comment by fredgan** [comment]
Hi, I have read  #437 and  #465 
`validate_module()` function has been removed from `add_parsed_module`. So this PR won't re-validate modules after transform. Since it has changed by #465 , I am wondering whether the original problem still exists. Maybe I understand wrong, but I need a clear testcase for this.

**Comment by wlupton** [comment]
Two more things:
* I should have been clear that the final example from the previous comment also fails in the same way on the `feature/transform-reset-env` branch
* We've got some YANG where the `edit` transform fails in `master` but succeeds in the `feature/transform-reset-env` branch

This makes me think that this PR does improve things but still isn't sufficient.

Please see output below. I'll see whether I can reproduce the second case(s) with simpler YANG.

(1)
```
lewa:test_transform% git remote -v
origin	https://github.com/BroadbandForum/pyang (fetch)
origin	https://github.com/BroadbandForum/pyang (push)
upstream	https://github.com/mbj4668/pyang (fetch)
upstream	https://github.com/mbj4668/pyang (push)

lewa:test_transform% git status
On branch feature/transform-reset-env
Your branch is up to date with 'origin/feature/transform-reset-env'.
nothing to commit, working tree clean

lewa:test_transform% pyang --plugindir . -t add-foo a.yang -f tree
module: a
Traceback (most recent call last):
  File "/Users/william/Development/pyang/default/bin/pyang", line 530, in <module>
    run()
  File "/Users/william/Development/pyang/default/bin/pyang", line 499, in run
    emit_obj.emit(ctx, modules, fd)
  File "/Users/william/Development/pyang/default/pyang/plugins/tree.py", line 85, in emit
    ctx.opts.tree_line_length, path)
  File "/Users/william/Development/pyang/default/pyang/plugins/tree.py", line 158, in emit_tree
    prefix_with_modname=ctx.opts.modname_prefix)
  File "/Users/william/Development/pyang/default/pyang/plugins/tree.py", line 322, in print_children
    width = get_width(0, i_children)
  File "/Users/william/Development/pyang/default/pyang/plugins/tree.py", line 310, in get_width
    if ch.i_module.i_modulename == module.i_modulename:
AttributeError: i_modulename
```

(2)
```
pyang --path=PATH --max-line-length=70 --keep-comments --transform=edit --format=yang --edit-yang-version=1.1 --edit-delete-import-dates --edit-namespace=%SUBST/broadband-forum-org/bbf --edit-organization=@../ORGANIZATION --edit-contact=@../CONTACT --edit-description=%SUMMARY+@../LICENSE+@../CONTEXT --edit-revision-description=%DELETE+@../REVISION --edit-revision-reference=%DELETE+@../REFERENCE --yang-line-length=70 --edit-delete-revisions-after=2018-12-03 --edit-revision-date=2019-10-21 bbf-ancp-fastdsl-access-extensions.yang >bbf-ancp-fastdsl-access-extensions.yang.edited
bbf-ancp-fastdsl-access-extensions.yang:376: error: node bbf-ancp-fastdsl-access-extensions::fastdsl-access-line-attribute is not found
bbf-ancp-fastdsl-access-extensions.yang:454: error: node bbf-ancp-fastdsl-access-extensions::fastdsl-access-line-attribute is not found
```

```
      uses fastdsl-access-line-attribute-config-parameters {
        refine fastdsl-access-line-attribute {    # <-- line 376
          min-elements 1;
        }
      }
```

```
          uses fastdsl-access-line-attribute-config-parameters {
            refine fastdsl-access-line-attribute {    # <-- line 454
              min-elements 1;
            }
          }
```

```
pyang --path=PATH--max-line-length=70 --keep-comments --transform=edit --format=yang --edit-yang-version=1.1 --edit-delete-import-dates --edit-namespace=%SUBST/broadband-forum-org/bbf --edit-organization=@./ORGANIZATION --edit-contact=@./CONTACT --edit-description=%SUMMARY+@./LICENSE+@./CONTEXT --edit-revision-description=%DELETE+@./REVISION --edit-revision-reference=%DELETE+@./REFERENCE --yang-line-length=70 --edit-delete-revisions-after=2019-02-25 --edit-revision-date=2020-01-31 bbf-xponani-power-management.yang >bbf-xponani-power-management.yang.edited
bbf-xponani-power-management.yang:6: warning: imported module "bbf-yang-types" not used
bbf-xponani-power-management.yang:9: warning: imported module "ietf-interfaces" not used
bbf-xponani-power-management.yang:12: warning: imported module "bbf-xponani" not used
bbf-xponani-power-management.yang:181: error: "bbf-xponani-power-management:power-management-profile" in the path for power-management-profile-ref at bbf-xponani-power-management.yang:178 is not found
```

```
      leaf power-management-profile-ref {    # <-- line 178
        type leafref {
          path '/xponani-power-management-profiles'
            + '/power-management-profile/name';    # <-- line 181
        }
```

**Comment by fredgan** [comment]
> Transforms can modify the statement tree, so I think there needs to be some way to check that the potentially-modified tree is correct. This validation is the default but can be suppressed by a `True` return value (so transforms that know they haven't modified the tree can return `True`; see the `pyang` executable for this logic).
> 
> Right now, most (all?) of the `test/test_transform` tests are failing. See the example below running in the latest GitHub master. Note that it works for the `yang` format but fails for the `tree` format.
> 
> Is this an adequate test case?
> 
> ```
> lewa:mbj4668% git log -1
> commit 10d5ec8dad6fec047edf5586676efac66557962a (HEAD -> master, origin/master, origin/HEAD)
> Author: fredgan <ganshaolong@vip.qq.com>
> Date:   Tue Apr 28 15:30:58 2020 +0800
> 
>     add a __tmp_augmnet__ target node
> 
> lewa:mbj4668% . env.sh 
> 
> lewa:mbj4668% cd test/test_transform/
> lewa:test_transform% pyang --plugindir . -t add-foo a.yang 
> lewa:test_transform% pyang --plugindir . -t add-foo a.yang -f yang
> module a {
>   namespace "urn:a";
>   prefix a;
> 
>   description
>     "module";
> 
>   container x {
>     description
>       "container";
>     leaf y {
>       type string;
>     }
>     leaf foo {
>       type string;
>     }
>   }
> }
> lewa:test_transform% pyang --plugindir . -t add-foo a.yang -f tree
> module: a
> Traceback (most recent call last):
>   File "/Users/william/Development/pyang/default/bin/pyang", line 530, in <module>
>     run()
>   File "/Users/william/Development/pyang/default/bin/pyang", line 499, in run
>     emit_obj.emit(ctx, modules, fd)
>   File "/Users/william/Development/pyang/default/pyang/plugins/tree.py", line 85, in emit
>     ctx.opts.tree_line_length, path)
>   File "/Users/william/Development/pyang/default/pyang/plugins/tree.py", line 158, in emit_tree
>     prefix_with_modname=ctx.opts.modname_prefix)
>   File "/Users/william/Development/pyang/default/pyang/plugins/tree.py", line 322, in print_children
>     width = get_width(0, i_children)
>   File "/Users/william/Development/pyang/default/pyang/plugins/tree.py", line 310, in get_width
>     if ch.i_module.i_modulename == module.i_modulename:
> AttributeError: i_modulename
> ```

Sorry for long time no reply because of a vocation.

From this command line, it seems that it is the latest master. Did you move your modification(this PR) to it? In fact, I have tried this case, `pyang --plugindir . -t add-foo a.yang -f tree`. No crash reported in master. That's why I ask for a clear case.

> Note that it works for the `yang` format but fails for the `tree` format.

I will try to write some other cases.

**Comment by wlupton** [comment]
Thanks @fredgan. This is very strange. I just tried again and still see the same thing. Here's the full transcript `indent-bug.yang` is from my #616 investigation).
```
Last login: Tue May  5 10:12:03 on ttys003
lewa:~% cd pyang/mbj4668/
/Users/william/Development/pyang/mbj4668

lewa:mbj4668% git remote -v
origin	https://github.com/mbj4668/pyang.git (fetch)
origin	https://github.com/mbj4668/pyang.git (push)

lewa:mbj4668% git fetch

lewa:mbj4668% git pull
Already up to date.

lewa:mbj4668% git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	indent-bug.yang

nothing added to commit but untracked files present (use "git add" to track)

lewa:mbj4668% git log -1
commit 10d5ec8dad6fec047edf5586676efac66557962a (HEAD -> master, origin/master, origin/HEAD)
Author: fredgan <ganshaolong@vip.qq.com>
Date:   Tue Apr 28 15:30:58 2020 +0800

    add a __tmp_augmnet__ target node

lewa:mbj4668% . env.sh 

lewa:mbj4668% which pyang
/Users/william/Development/pyang/mbj4668/bin/pyang

lewa:mbj4668% cd test/test_transform/
/Users/william/Development/pyang/mbj4668/test/test_transform

lewa:test_transform% pyang --plugindir . -t add-foo a.yang -f tree
module: a
Traceback (most recent call last):
  File "/Users/william/Development/pyang/default/bin/pyang", line 530, in <module>
    run()
  File "/Users/william/Development/pyang/default/bin/pyang", line 499, in run
    emit_obj.emit(ctx, modules, fd)
  File "/Users/william/Development/pyang/default/pyang/plugins/tree.py", line 85, in emit
    ctx.opts.tree_line_length, path)
  File "/Users/william/Development/pyang/default/pyang/plugins/tree.py", line 158, in emit_tree
    prefix_with_modname=ctx.opts.modname_prefix)
  File "/Users/william/Development/pyang/default/pyang/plugins/tree.py", line 322, in print_children
    width = get_width(0, i_children)
  File "/Users/william/Development/pyang/default/pyang/plugins/tree.py", line 310, in get_width
    if ch.i_module.i_modulename == module.i_modulename:
AttributeError: i_modulename
lewa:test_transform% 
```

**Comment by wlupton** [comment]
@fredgan , the problem is my stupid `pyang` alias error (see #616). I am very sorry about this.

I confirm that this is fine in `master`:
```
% pyang --plugindir . -t add-foo a.yang -f tree
module: a
  +--rw x
     +--rw y?     string
     +--rw foo?   string
```

I'll add a further comment about test cases.

**Comment by wlupton** [comment]
The other cases still fail for us in `master` but not in `feature/transform-reset-env`. As promised earlier, I'll look into providing simpler YANG that fails in the same way or (failing that) into making available the necessary YANG.

**Comment by wlupton** [comment]
(no changes; just a rebase against the latest master)

**Comment by wlupton** [comment]
I've managed to create simpler YANG that produces the same errors that I reported earlier. I suspect that there might be a single underlying problem relating to groupings (and that the 'module not used' warning might be a consequence of this)?

Running in `master` with the YANG shown at the bottom (and the same `null.py` as before):
```
% pyang --plugindir . -f yang grouping-bug.yang >/dev/null
<no errors>

% pyang --plugindir . -t null -f yang grouping-bug.yang >/dev/null
grouping-bug.yang:5: warning: imported module "ietf-yang-types" not used
grouping-bug.yang:25: error: "grouping-bug:name" in the path for profile-ref at grouping-bug.yang:23 is not found
```

```
% pyang --plugindir . -f yang refine-bug.yang >/dev/null
<no errors>

% pyang --plugindir . -t null -f yang refine-bug.yang >/dev/null
refine-bug.yang:13: error: node refine-bug::attr is not found
```

grouping-bug.yang:

```
module grouping-bug {
  namespace "urn:grouping-bug";
  prefix grouping-bug;

  import ietf-yang-types {
    prefix yang;
  }

  grouping profiles-data {
    leaf name {
      type yang:yang-identifier;
    }
  }

  container root {
  }

  container profiles {
    uses profiles-data;
  }

  augment "/root" {
    leaf profile-ref {
      type leafref {
        path '/profiles/name';
      }
    }
  }
}
```

refine-bug.yang

```
module refine-bug {
  namespace "urn:refine-bug";
  prefix "refine-bug";

  grouping stuff {
    leaf-list attr {
      type string;
    }
  }

  container root {
    uses stuff {
      refine attr {
      }
    }
  }
}
```

null.py

```
from pyang import plugin

def pyang_plugin_init():
    plugin.register_plugin(Null())

class Null(plugin.PyangPlugin):
    def add_transform(self, xforms):
        xforms['null'] = self

    def transform(self, ctx, modules):
        pass
```

**Comment by wlupton** [comment]
@fredgan, any thoughts on this? Can I help? Thanks.

**Comment by fredgan** [comment]
@wlupton Sorry for busy these days. Your last cases make sense for reproducing the problem, thanks a lot. I will research it. Feel free to discuss it if you have any idea.

**Comment by wlupton** [comment]
@fredgan and @mbj4668, I'd like to propose that this PR be merged. Why?

* I just rebased against the latest master and nothing has changed: the problems described above still occur in master, and are fixed in this branch
* The fixes in this branch (for which I take no credit!) are quite simple and it's easy to see why they might fix the problem even without knowing exactly what the problem was
* The fixes will *only* have any effect when performing transforms, i.e., any bad effects should be quite limited

If you agree, please merge! Thanks.

**Comment by wlupton** [comment]
I just realised that there seems to be a problem with the unconditional call to `ctx.internal_reset()`. This clears out errors, and the post-transform validation doesn't seem to put them back again.

I'll take a closer look at this...

**Comment by wlupton** [comment]
I've looked at this, and pushed some tentative fixes. There were several problems:

1. `Statement.internal_reset()` was using `__slots__`, but this is only the class's _additional_ slots, so it's necessary to walk up the inheritance tree

2. `ModSubmodStatement.__init__()` sets `i_is_validated` to `False`, so we need a `ModSubmodStatement.internal_reset()` that does the same thing (various places in the code assume that modules have defined `i_is_validated` attributes)

3. Just calling `Context.add_parsed_module(module)` after the transform isn't sufficient, because this doesn't re-validate. I think it's necessary to call `Context.validate()` (and, for good measure, `ModSubmodStatement.prune()`). This needs to be done after each transform that might have modified the node hierarchy

With the above fixes, the `test_transform` tests pass, and the above `grouping-bug.yang` and `refine-bug.yang` problems are fixed, but...

Types and groupings might not be found. I have realized that this is a consequence of `augment` sometimes re-parenting nodes. This of course isn't undone when the modules are reset, so searching up the node hierarchy (after the module reset and re-validation) can go to the module that defined the node that's being augmented rather than the module in which the augmentation is defined.

(Why "sometimes"? I didn't look into this, but the re-parenting only seems to occur when the augmentation includes a container? Something like this anyway.)

`augment-bug.yang` (quoted below) shows this problem. With just the above fixes:

```
% pyang augment-bug.yang
<no output>
```

```
% pyang --plugindir . -t null augment-bug.yang
augment-bug.yang:21: error: type "aardvark" not found in module "augment-bug"
augment-bug.yang:31: error: grouping "bison" not found in module "augment-bug"
```

With the above fixes plus additional fixes to `statements.search_typedef()` and `statements.search_grouping()` the errors go away.

These latter fixes fall back on searching the original module if searching the original statement (and its parent etc.) don't find the typedef or grouping. This isn't a complete fix but it fixes these problems and other real-world instances of similar problems in Broadband Forum YANG modules. I think perhaps a "proper" fix would avoid re-parenting nodes in the first place, e.g., instead use an `i_parent` attribute, but I haven't looked into this.

The fixes appear to address the known problems, but I don't think we're quite done here. `Context.internal_reset()` is called unconditionally before the transforms are called, but if all the transforms return `True` there won't be any re-validation. Therefore I think that transforms should indicate via the `Transform.setup_xform()` result whether or not they will modify the node tree and therefore require re-validation. This information, rather than the `Transform.transform()` result, can control whether `Context.internal_reset()` is called before running the transforms, and whether to re-validate after each transform. I think this can be implemented backwards compatibly (and propose doing so via a separate pull request if/when this one has been merged).

As I write this, the checks are still running. I just fixed a problem, and I think they'll complete successfully now..

**Any thoughts on all this?**

```
module augment-bug {
  namespace "urn:augment-bug";
  prefix augment-bug;

  import ietf-interfaces {
    prefix if;
  }

  typedef aardvark {
    type uint32;
  }

  grouping bison {
    leaf cougar {
      type uint32;
    }
  }

  augment "/if:interfaces/if:interface" {
    leaf dingo {
      type aardvark;
    }
  }

  augment "/if:interfaces/if:interface" {
    uses bison;
  }

  augment "/if:interfaces/if:interface" {
    container echidna {
      uses bison;
    }
  }
}
```

**Comment by mbj4668** [comment]
I have looked at this, and I agree that the re-parenting probably is a mistake.  But I think that you proposed solution is good enough.

Could you add the various modules you have experimented with as proper tests?  For example augement-module.yang and test that null.py doesn't give any errors?

**Comment by wlupton** [comment]
I have updated the tests as requested.

I also decided to try to address my earlier 'but I don't think we're quite done here' comment (from [here](https://github.com/mbj4668/pyang/pull/580#issuecomment-773390780)). I started to implement my proposal but it became clear that it's both over-complex and wrong, so I decided simply to move `ctx.internal_reset()` inside the transform loop. As far as I can tell, this works fine, and it means that all transforms see a fully validated node tree with all the magic i_ variables fully populated (which wasn't the case before).

(I also took the liberty of fixing a couple of `edit` transform `statements.Statement()` constructor calls to be the recommended `statements.new_statement()` calls.)

**Pull request merged**
