### PR TITLE
Update check-update-from option according to RFC 7950 section 11

### PR DESCRIPTION
**Pull request by yang-catalog**
Max elements statement can be removed

    Prefix change with base statements
    caused the error. This is fixed

    If-feature can be removed if note is
    not mandatory

    Base statement can be added to identity

    Base statement can be removed from identityref

    Config change to true only if mandatory had
    not existing variable

Signed-off-by: miroslav.kovac <miroslav.kovac@pantheon.tech>

### CODE REVIEW

**Comment by yang-catalog** [comment]
Hi @mbj4668 

This seemes to fail only because of the coverage decreased by 1 percent.. is this something that could be merged or do I have to create tests for that so the coverage will increase by 1 percent again?

thank you
Miroslav Kovac

**Comment by mbj4668** [comment]
Hi,

No, I won't reject a PR due to decreased coverage.  I'll have a look at
this PR shortly.  Thanks for contributing!


/martin

Den mån 10 sep. 2018 kl 17:19 skrev yang-catalog <notifications@github.com>:

**Comment by mbj4668** [comment]
Hi,
It would be great if you also could add test cases for these changes, you could e.g. update "test/test_update".
BTW, is this supposed to be complete in terms of the 7950 update rules?  I think there is one thing missing:

   o  A "when" statement may be removed or its constraint relaxed.

but it needs to be allowed only for a 1.1 module

/martin

**Comment by yang-catalog** [comment]
Hi @mbj4668 test is update and when is added.. you were right I missed that one thank you.. And yes it is according to 7950 rules and should be complete now..

thank you
Miroslav K.

**Comment by mbj4668** [comment]
Thanks for the contribution!

**Pull request merged**
