### PR TITLE
Fix issue 430

### PR DESCRIPTION
**Pull request by yang-catalog**
Signed-off-by: miroslav.kovac <miroslav.kovac@pantheon.tech>

### CODE REVIEW

**Comment by mbj4668** [comment]
Try with this:

module a {
  namespace urn:a;
  prefix a;

  container a {
    must "e-band != 'and-2'";
    leaf e-band {type string;}
    leaf earfcn {type int32;}
  }
}

I don't think your fix fixes this.

**Comment by mbj4668** [comment]
can you add that must expression to the test as well?

**Comment by yang-catalog** [comment]
sure

**Comment by yang-catalog** [comment]
done

**Pull request merged**
