### PR TITLE
Fix grouping deviation issue

### PR DESCRIPTION
**Pull request by HuaianZhou**
Please help review the fix.

### CODE REVIEW

**Comment by llhotka** [comment]
Travis check fails on your code. You can see it yourself by running `make` in the directory `test/test_dsdl`, or simply by running
```
pyang -f dsdl ll-list.yin
```
in that directory.

**Comment by HuaianZhou** [comment]
Thanks!
I can reproduce the problem in my PC.

**Comment by HuaianZhou** [comment]
Do I need add some test case to cover my code ?

**Comment by llhotka** [comment]
You can, but in any case your code should pass all the tests that are already there.

**Comment by llhotka** [comment]
Merged your changes, thanks a lot!

**Comment by llhotka** [comment]
I had to remove your changes because they cause issue #208 – contents of a *refine* statement appear twice in the generated hybrid schema (see the `<nma:must>` annotation in the example below).
```
$ cat refine.yang 
module refine {
  namespace "http://example.com/refine";
  prefix rf;

  grouping grp {
    leaf foo {
      type string;
    }
  }

  uses grp {
    refine "foo" {
      must ". = 'hi'";
    }
  }
}
$ pyang -f dsdl refine.yang | xmllint --format -
<?xml version="1.0" encoding="UTF-8"?>
<grammar xmlns="http://relaxng.org/ns/structure/1.0"
    xmlns:nma="urn:ietf:params:xml:ns:netmod:dsdl-annotations:1"
    xmlns:rf="http://example.com/refine"
    xmlns:a="http://relaxng.org/ns/compatibility/annotations/1.0"
    xmlns:dc="http://purl.org/dc/terms"
    datatypeLibrary="http://www.w3.org/2001/XMLSchema-datatypes">
  <dc:date>2016-05-09</dc:date>
  <start>
    <grammar nma:module="refine" ns="http://example.com/refine">
      <dc:source>YANG module 'refine'</dc:source>
      <start>
        <nma:data>
          <optional>
            <element name="rf:foo">
              <nma:must assert=". = 'hi'"/>
              <nma:must assert=". = 'hi'"/>
              <data type="string"/>
            </element>
          </optional>
        </nma:data>
        <nma:rpcs/>
        <nma:notifications/>
      </start>
    </grammar>
  </start>
</grammar>
```

**Pull request merged**
