### PR TITLE
pyang logo

### PR DESCRIPTION
**Pull request by vkosuri**
pyanglogo

### CODE REVIEW

**Comment by vkosuri** [comment]
Any comment/improvements on this PR?

**Comment by kwatsen** [comment]
I didn't even know pyang had a logo.  I always just use the command line  ;)

**Comment by mbj4668** [comment]
@kwatsen: no pyang doesn't have a logo.  this seems to be a request to add one.

@vkosuri: To be honest, I don't really like this logo...

**Comment by vkosuri** [comment]
@mbj4668 Thanks, does it make sense?

```
_ __  _   _  __ _ _ __   __ _ 
| '_ \| | | |/ _` | '_ \ / _` |
| |_) | |_| | (_| | | | | (_| |
| .__/ \__, |\__,_|_| |_|\__, |
| |     __/ |             __/ |
|_|    |___/             |___/ 
```

**Pull request closed without merging**
