### PR TITLE
Fix for https://github.com/mbj4668/pyang/issues/126

### PR DESCRIPTION
**Pull request by aakash01**
possible fix for Extensions ignored in YIN format.

Steps to reproduce: 

**amodule.yang**

``` module amodule {
    yang-version 1;
  namespace "http://test.com/amodule";
  prefix am;

  import bmodule {
    prefix bm;
  }  
  container test {
        uses bm:test;
  }
} ```

**bmodule.yang**
``` module bmodule {
    yang-version 1;
  namespace "http://test.com/bmodule";
  prefix bm;

  import extension {
    prefix ext;
  }

  grouping test {
        ext:abc "some value";
        leaf a {
            type string;
        }
  }
}```

**extension.yang**
``` module extension {
    yang-version 1;
  namespace "http://test.com/ext";
  prefix ext;

  extension abc {
      argument path;
      description
        "extension abc";
    }
}```

> pyang -f yin -o amodule.yin amodule.yang
> 
> .\bmodule.yin:13:  error: no module with the namespace "http://test.com/ext" is imported

### CODE REVIEW

**Comment by aakash01** [comment]
Can we include this commit and bump up the pyang version?

**Comment by aakash01** [comment]
@mbj4668 , Can you please update on this pull request?

**Comment by mbj4668** [comment]
This fix looks good.  Could you also please add a test case that fails w/o you fix, but works with it?

**Comment by mbj4668** [comment]
Different fix in 1e7f145.

**Pull request closed without merging**
