### PR TITLE
Flatten plugin

### PR DESCRIPTION
**Pull request by remingtonc**
Plugin which parses schema and outputs RFC 8040 XPath, primitive type, config permission, deviation status, and description; as well as filter for only leaves and/or certain config properties.

Uses `csv.writer` for writing output to `fd`.

```bash
(pyang) [9.3-1] pyang -f flatten ietf-interfaces.yang                        fix-ietf-types-cisco  ✱
/ietf-interfaces:interfaces
/ietf-interfaces:interfaces/interface
/ietf-interfaces:interfaces/interface/name
/ietf-interfaces:interfaces/interface/description
/ietf-interfaces:interfaces/interface/type
/ietf-interfaces:interfaces/interface/enabled
/ietf-interfaces:interfaces/interface/link-up-down-trap-enable
...
```

If there's any incorrect terminology, etc. happy to modify.

### CODE REVIEW

**Comment by mbj4668** [comment]
Hi,  This looks useful.  I would appreciate if you could write some tests and update the man page with info about this plugin as well.

**Comment by remingtonc** [comment]
Sure. Took a quick look at the tests dir, I think I see the workflow, I'll try and put something together.

**Comment by mbj4668** [comment]
I noticed that you wrote some documentation of the new command line parameters as comments in the code.  This documentation should go into the man page (doc/pyang.1.dbk).  Compare with the other plugins like tree, depend, sid etc.

**Comment by remingtonc** [comment]
@mbj4668 I believe this is now ready for more substantial review. Docs are present.

**Comment by mbj4668** [comment]
One comment.  I don't think the term "permission" is correct.  It is rather the config property; config false doesn't mean that someone doesn't have permission to write, it means that the node models state.
So a simple fix would be to call it '--flatten-config'.  But then I tried:

    pyang -f flatten --flatten-data-keywords  --flatten-permission modules/ietf/ietf-system.yang 

which returns (at the end):

    /ietf-system:set-current-datetime,ro

This is misleading; it is an RPC, not config false.  The tree plugin prints:

      +---x set-current-datetime

So perhaps align with the tree plugin and print:

    /ietf-system:set-current-datetime,x

RFC 8340 refers to this as "flags".   So perhaps --flatten-flags?

**Comment by remingtonc** [comment]
Martin, that makes sense. I'll look at how to implement.

**Comment by remingtonc** [comment]
@mbj4668 Changed from "permission" to "flag" - copied from `tree` plugin. However I did not retain the `mode` aspect of the method. I see some [special handlings](https://github.com/mbj4668/pyang/blob/master/pyang/plugins/tree.py#L176-L182) in the `tree` plugin around augmentations - I'm simply checking the current node `keyword`. Would this present incorrect output?

**Comment by remingtonc** [comment]
@mbj4668 Martin, RPC `input`/`output` is now more correctly handled/flagged. If you're willing to check it out, would appreciate.

**Comment by remingtonc** [comment]
Would like to call out that am [appending](https://github.com/mbj4668/pyang/pull/519/files#diff-46bcf771159cd94396011ed19d7b3707R172) `input` and `output` to nodes to traverse for RPCs - do you foresee any issues with this approach? Otherwise options were not output.

**Comment by mbj4668** [comment]
FYI, I did some cleanup, see the branch mbj/flatten2.  I will merge this branch to master.

**Comment by remingtonc** [comment]
@mbj4668 I'll take it, if it gets into the tree. :) Feel free to close this pull request upon merge.

**Pull request merged**
