### PR TITLE
Add Statement utility functions

### PR DESCRIPTION
**Pull request by remingtonc**
`mk_path_str` did not have the necessary XPath-constructing kind of functionality required to meet the different permutations of how one might have implemented XPaths. Some have implemented it to be based on prefix, some on module, some both, ... I needed the flexibility to determine the module-prefixed XPath, or the prefix-prefixed, etc. This adds functionality to the `mk_path_str`, while keeping original behaviors, to enable more robust path-making.

So this pull request adds some utility functions which enable permutations of:

__Original Behavior__
* `mk_path_str(stmt)`  
`/root/node/node/...`

__`get_xpath`__
This is satisfying what I have seen as the typical desired behavior adding the prefix/module to the node when it changes mid-xpath.
Adds prefixes when the prefix/module changes.
* `mk_path_str(stmt, prefix_onchange=True, prefix_to_module=True)`  
`/module:root/node/module:node/...`
* `mk_path_str(stmt, prefix_onchange=True)`  
`/prefix:root/node/prefix:node/...`
* `mk_path_str(stmt, prefix_onchange=True, resolve_top_prefix_to_module=True)`  
`/module:root/node/prefix:node/...`

`qualified=True` adds prefix/module to every node.
* `mk_path_str(stmt, with_prefixes=True, prefix_to_module=True)`  
`/module:root/module:node/module:node/...`
* `mk_path_str(stmt, with_prefixes=True)`  
`/prefix:root/prefix:node/prefix:node/...`
* `mk_path_str(stmt, with_prefixes=True, resolve_top_prefix_to_module=True)`  
`/module:root/prefix:node/prefix:node/...`

As well as helpers to `get_description`, `get_type` (`type`), `get_qualified_type` (`i_orig_module:type`), and `get_primitive_type` (`uint8`).

This also adds a function `mk_path_list` which returns a list of tuples containing the (`module`, `prefix`, `node`) that can be parsed into an XPath or more custom parsing that requires knowledge of the module, prefix, and node all at once.

I'm fine with keeping some of the helpers out of tree, but I am a huge fan of the new `mk_path_str`, `mk_path_list`, and `get_primitive_type` helpers.

Please keep in mind I am also just well enough informed to potentially be helpful, and yet completely uncertain. Thanks for working with me on it!

Not sure where to add tests. Derived from https://github.com/remingtonc/pyang-as-lib

### CODE REVIEW

**Comment by remingtonc** [comment]
This pull request has added more content.
Hoping for a generic bit of feedback - should an XPath include prefixes if the prefix changes when deriving the XPath? e.g.
`/openconfig-interfaces:interfaces/interface/openconfig-if-ethernet:ethernet/state/counters` (using modules)

**Comment by mbj4668** [comment]
It would be useful with some description / documentation of these functions.  It is not clear what an "xpath path" really is.  It is also not clear what an RFC 8040 xpath path is.

**Comment by glennmatthews** [comment]
It would probably be more Pythonic to implement these various `get_*` methods as `@property`s of the `Statement` class.

**Comment by remingtonc** [comment]
@mbj4668 `mk_path_str` did not have the necessary XPath-constructing kind of functionality required to meet the different permutations of how one might have implemented XPaths. Some have implemented it to be based on prefix, some on module, some both, ... I needed the flexibility to determine the module-prefixed XPath, or the prefix-prefixed, etc. This adds functionality to the `mk_path_str`, while keeping original behaviors (as of this morning), to enable more robust path-making. Apologies on "xpath path" - "path" was used in leiu of xpath in the code and I was frankly uncertain if path was actually xpath or there could be other kinds of paths with YANG.

Regarding the RFC 8040 XPath, that is the module-prefixed XPath (I believe).
[RFC 8040, Section 3.5.3](https://tools.ietf.org/html/rfc8040#section-3.5.3)
> If a node in the path is defined in a module other than its parent node or its parent is the datastore, then the module name followed by a colon character (":") MUST be prepended to the node name in the resource identifier.

This is also important regarding [RFC 7951, Section 4](https://tools.ietf.org/html/rfc7951#section-4):


> namespace-qualified - the data node identifier is prefixed with the name of the module in which the data node is defined, separated from the data node identifier by the colon character (":").

> ...

> The name of a module determines the namespace of all data node names defined in that module. If a data node is defined in a submodule, then the namespace-qualified member name uses the name of the main module to which the submodule belongs.

> ...

> A namespace-qualified member name MUST be used for all members of a top-level JSON object and then also whenever the namespaces of the data node and its parent node are different. In all other cases, the simple form of the member name MUST be used.

So this pull request adds some utility functions which enable permutations of:

__Original Behavior__
* `mk_path_str(stmt)`  
`/root/node/node/...`

__`get_xpath`__
This is satisfying what I have seen as the typical desired behavior adding the prefix/module to the node when it changes mid-xpath.
Adds prefixes when the prefix/module changes.
* `mk_path_str(stmt, prefix_onchange=True, prefix_to_module=True)`  
`/module:root/node/module:node/...`
* `mk_path_str(stmt, prefix_onchange=True)`  
`/prefix:root/node/prefix:node/...`
* `mk_path_str(stmt, prefix_onchange=True, resolve_top_prefix_to_module=True)`  
`/module:root/node/prefix:node/...`

`qualified=True` adds prefix/module to every node.
* `mk_path_str(stmt, with_prefixes=True, prefix_to_module=True)`  
`/module:root/module:node/module:node/...`
* `mk_path_str(stmt, with_prefixes=True)`  
`/prefix:root/prefix:node/prefix:node/...`
* `mk_path_str(stmt, with_prefixes=True, resolve_top_prefix_to_module=True)`  
`/module:root/prefix:node/prefix:node/...`

As well as helpers to `get_description`, `get_type` (`type`), `get_qualified_type` (`i_orig_module:type`), and `get_primitive_type` (`uint8`).

This also adds a function `mk_path_list` which returns a list of tuples containing the (`module`, `prefix`, `node`) that can be parsed into an XPath or more custom parsing that requires knowledge of the module, prefix, and node all at once.

I'm fine with keeping some of the helpers out of tree, but I am a huge fan of the new `mk_path_str`, `mk_path_list`, and `get_primitive_type` helpers.

Please keep in mind I am also just well enough informed to potentially be helpful, and yet completely uncertain. Thanks for working with me on it!

**Pull request merged**
