### PR TITLE
Integrate with travis-ci.

### PR DESCRIPTION
**Pull request by lpenz**
- .travis.yml that runs the tests in travis-ci
- show build status in README.md
- .gitignore test results
- test .gitignore

### CODE REVIEW

**Comment by mbj4668** [comment]
Thanks!

**Comment by lpenz** [comment]
Hi!

There is a little bit of setup that must be done in the account level to enable travis:
http://docs.travis-ci.com/user/getting-started/

Namely, I think the following is enough:
- sign in travis-ci.org with your GitHub account
- go to https://travis-ci.org/profile, force a refresh and enable travis-ci for the repository
- the next commit will trigger travis-ci

**Comment by mbj4668** [comment]
Everything seems to work just fine (and I got to fix an old bug in order to have something to push ;)
Thanks again!

**Comment by lpenz** [comment]
Yes, perfectly!

**Pull request merged**
