### PR TITLE
Output status value in flatten plugin

### PR DESCRIPTION
**Pull request by remingtonc**
Adds the `--flatten-status` flag to the `flatten` plugin which will output the `status` of the XPath. `current` by default, `deprecated`, or `obsolete`.

### CODE REVIEW

**Comment by fredgan** [comment]
You have added some distinct option to flatten plugin. Maybe these distinct options can be tested simultaneously in one test case in order to reduce test time. How do you think?

**Comment by remingtonc** [comment]
@fredgan We certainly could, but the current parsing is rather small timing at ~5 seconds total.

`make  3.35s user 0.60s system 90% cpu 4.376 total`

If you would like me to consolidate into a single test I would prefer to do it as its own PR, however.

**Comment by fredgan** [comment]
Please rebase the master branch and re-commit

**Comment by remingtonc** [comment]
Done!

**Comment by fredgan** [comment]
Still have some conflicts need to be solved

**Comment by remingtonc** [comment]
Are you sure? Seems to merge without conflict via CLI at least.

```
[pyang] git checkout master                            flatten-output-status  ✱
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
[pyang] git branch mtest                                              master  ✱
[pyang] git checkout mtest                                            master  ✱
Switched to branch 'mtest'
[pyang] git merge flatten-output-status                                mtest  ✱
Updating 6f08bb1..e09eef5
Fast-forward
 doc/pyang.1.dbk                                    |  8 +++
 man/man1/pyang.1                                   |  5 ++
 pyang/plugins/flatten.py                           | 17 ++++++
 test/test_flatten/Makefile                         |  5 +-
 .../benchmarks/ietf-interfaces.status.csv          | 61 ++++++++++++++++++++++
 5 files changed, 95 insertions(+), 1 deletion(-)
 create mode 100644 test/test_flatten/benchmarks/ietf-interfaces.status.csv
```

**Comment by fredgan** [comment]
I choose the wrong merge option. It's OK now.

**Pull request merged**
