### PR TITLE
Add option to output keys in flatten plugin

### PR DESCRIPTION
**Pull request by remingtonc**
Adds `--flatten-keys` and `--flatten-keys-in-xpath` to `flatten` plugin.

* `--flatten-keys` will output `key` for each XPath that is identified as a key.
* `--flatten-keys-in-xpath` will output keys in-XPath in brackets i.e. `node[key_name]`.

This PR also adds `statements.get_keys()` and modifies `statements.mk_path_str`, `statements.mk_path_list`, and `statements.get_xpath` with a `with_keys` flag.

e.g.
```
(pyang) [653] pyang -f flatten --hello capabilities-xrv9k.xml --flatten-keys --flatten-keys-in-xpath > xrv9k.flat6
...
/Cisco-IOS-XR-infra-syslog-cfg:syslog/Cisco-IOS-XR-infra-correlator-cfg:suppression/rules/rule[name]/alarm-causes/alarm-cause[category][group][code],
/Cisco-IOS-XR-infra-syslog-cfg:syslog/Cisco-IOS-XR-infra-correlator-cfg:suppression/rules/rule[name]/alarm-causes/alarm-cause[category][group][code]/category,key
/Cisco-IOS-XR-infra-syslog-cfg:syslog/Cisco-IOS-XR-infra-correlator-cfg:suppression/rules/rule[name]/alarm-causes/alarm-cause[category][group][code]/group,key
/Cisco-IOS-XR-infra-syslog-cfg:syslog/Cisco-IOS-XR-infra-correlator-cfg:suppression/rules/rule[name]/alarm-causes/alarm-cause[category][group][code]/code,key
```

### CODE REVIEW

**Comment by fredgan** [comment]
Please follow the `CONTRIBUTING` rules:
> Do not introduce trailing whitespace.
> Do not introduce lines longer than 80 characters.

**Comment by fredgan** [comment]
@remingtonc Would you mind adding some test cases to `test/test_flatten` for your new codes?

**Comment by remingtonc** [comment]
@fredgan Done!

**Comment by remingtonc** [comment]
I will raise my own concern - I am modifying the `statements.get_xpath` related methods to output a format like:
`/Cisco-IOS-XR-infra-syslog-cfg:syslog/Cisco-IOS-XR-infra-correlator-cfg:suppression/rules/rule[name]/alarm-causes/alarm-cause[category][group][code]/category` - I am not certain if the bracked notation is "valid" in the sense of XPaths. If I need to duplicate some code into the plugin to not change `statements` behavior happy to do so. But it is handy to understand what keys are desired in the XPath - just not certain of the appropriate notation to indicate that kind of meta-information while not specifying values. Based on XPath 1.0 reading, it looks like it might be valid, and indicate "get all elements which have 1 or more of these keys available", which seems correct to me.

**Comment by remingtonc** [comment]
PS any thoughts on when a new release will be cut? Even without this PR, would love to simply `pip install pyang` instead of point to source for `flatten` plugin.

**Pull request merged**
