### PR TITLE
YANG 1.1 support added to the sid plugin.

### PR DESCRIPTION
**Pull request by lemikev**
Support for anydata, action and notification added to the sid plugin.

### CODE REVIEW

**Comment by mbj4668** [comment]
Hi.  I will apply this pull request, but I would also appreciate if you could add the new -f sid to the documentation (man page).

**Comment by lemikev** [comment]
About the request to add the new -f sid to the documentation (man page). In which file or directory this information need to be added? Note that this plugin do not implement -f, it implement --generate-sid-file, --update-sid-file and --check-sid-file instead, see -help-sid output bellow:

> pyang --sid-help

Structure IDentifier (SID) are used to map YANG definitions to
CBOR encoding. These SIDs can be automatically generated
for a YANG module using the pyang sid plugin.

   pyang --generate-sid-file <entry-point:size> <yang-module>

For example:
   pyang --generate-sid-file 20000:100 toaster@2009-11-20.yang

The name of the .sid file generated is:

   <module-name>@<module-revision>.sid

Each time new items(s) are added to a YANG module by the
introduction of a new revision of this module, its included
sub-module(s) or imported module(s), the .sid file need to be
updated. This is done by providing the name of the previous
.sid file as argument.

   pyang --update-sid-file <file-name> <yang-module>

For example:
   pyang --update-sid-file toaster@2009-11-20.sid toaster@2009-12-28.yang

The --check-sid-file option can be used at any time to verify
if the .sid file need to be updated.

   pyang --check-sid-file <file-name> <yang-module>

The --list_sid option can be included before any of the previous
option to obtains the list of SIDs assigned or validated.

For example:
   pyang --list-sid --generate-sid-file 20000:100 toaster@2009-11-20.yang

**Comment by mbj4668** [comment]
lemikev <notifications@github.com> wrote:
> About the request to add the new -f sid to the documentation (man
> page). In which file or directory this information need to be added?
> Note that this plugin do not implement -f, it implement
> --generate-sid-file, --update-sid-file and --check-sid-file instead,
> see -help-sid output bellow:

Hmm, I was too quick in accepting the first pull request...

The preferred way to generate output from pyang is to use -f sid.  If
you need additional sid-specific parameters, use --sid-...

- At this point, I realized that the best way to handle this is to
revert the original pull request (done), and then you re-create the
pull request, and we have the discussion there.

Sorry for detecting this a bit late :(


/martin

**Comment by lemikev** [comment]
My first version was based on the -f option. After using it for some time, I moved to --generate-sid-file, --update-sid-file and --check-sid-file to greatly improve user experience. With this approach, the stdout and stderr are still available to summarize the operation and the sid file are automatically created, updated or verify using the correct name. I'll appreciate to keep this interface with is conform to the plugin interface post_validate_ctx().

Output example #1:
File toaster@2009-11-20.sid created
Number of SIDs available : 100
Number of SIDs assigned : 17

Output example #2:
File toaster@2009-12-28.sid updated
Number of SIDs available : 100
Number of SIDs assigned : 19

Output example #2:
Checking consistency of 'toaster@2009-12-28.sid'

SID        Assigned to
---------  --------------------------------------------------
20000      identity /toast-type
20001      identity /toast-type/frozen-bagel
20002      identity /toast-type/frozen-waffle
20003      identity /toast-type/hash-brown
20004      identity /toast-type/wheat-bread
20005      identity /toast-type/white-bread
20006      identity /toast-type/wonder-bread
20017      identity /toast-type/croisant
20007      node /toaster-info
20008      node /toaster-info/toaster-manufacturer (Remove)
20009      node /toaster-info/toaster-model-number
20010      node /toaster-info/toaster-status
20018      node /toaster-info/power-source/electric/voltage
20011      notification /toast-done
20012      notification /toast-done/toast-status
20013      rpc /cancel-toast
20014      rpc /make-toast
20015      rpc /make-toast/input/toaster-doneness
20016      rpc /make-toast/input/toaster-toast-type

WARNING, obsolete definitions should be defined as 'deprecated' or 'obsolete'.
Check completed successfully

**Comment by mbj4668** [comment]
Hi,

Please re-create your pull request (or update this one to be "New sid
plugin"), so we can have the discussion in the proper place.  I am
sorry I missed this originally.


/martin

**Comment by lemikev** [comment]
Re-creating the pull request as requested.

**Pull request closed without merging**
