### PR TITLE
Suppress unwanted errors

### PR DESCRIPTION
**Pull request by wlupton**
When there are multiple revisions of an imported module, they are all parsed, and the logic to suppress errors fails to suppress them from the revisions that aren't selected for import. This fix works around this.

Update: As I realised when I tried to create a test, there's a bit more to it than this.

I'll add a test and further explanation...

### CODE REVIEW

**Comment by wlupton** [comment]
This is trickier that I had realised. Whether or not the error occurs seems to depend on the order in which `os.listdir()` returns its results.

With the following temporary changes (the second one is to _undo_ the effect of the fix so the error can be seen!):

```
% git diff pyang/repository.py
diff --git a/pyang/repository.py b/pyang/repository.py
index e344562..e6d7c9b 100644
--- a/pyang/repository.py
+++ b/pyang/repository.py
@@ -112,7 +112,7 @@ class FileRepository(Repository):
         self.modules = []
         def add_files_from_dir(d):
             try:
-                files = os.listdir(d)
+                files = reversed(sorted(os.listdir(d)))
             except OSError:
                 files = []
             for fname in files:
```

```
% git diff bin/pyang
diff --git a/bin/pyang b/bin/pyang
index 2b71445..3040858 100755
--- a/bin/pyang
+++ b/bin/pyang
@@ -451,6 +451,8 @@ Validates the YANG module in <filename> (or stdin), and all its dependencies."""
             continue
         if (ctx.implicit_errors is False and
             epos.top.arg not in modulenames and
+            hasattr(epos.top, 'i_modulename') and
+            epos.top.i_modulename not in modulenames and
             (not hasattr(epos.top, 'i_modulename') or
              epos.top.i_modulename not in modulenames) and
             epos.ref not in filenames):
```

Then the new `test_i680` shows the failure

```
test_i680% pyang --max-line-len=70 -f tree -o mod1.tree mod1.yang -V
# module search path: .:/Users/william/Development/pyang/feature/modules:/Users/william/yang/modules:/System/Library/Frameworks/Python.framework/Versions/2.7/share/yang/modules
# read mod1.yang (CL)
# read mod2.yang
# READ mod2@2020-10-06.yang
mod2.yang:10: warning: line length 79 exceeds 70 characters
```

The logic that means that `mod2@2020-10-06.yang` is read is rather non-obvious. It doesn't happen in the initial `_get_latest_rev` because it's got an explicit rev in the filename, but happens later in `add_module`, probably because (thanks to the reversed sort) it's listed before `mod2.yang`.

Commit 94fc31c shows the above.

**Comment by wlupton** [comment]
Reverting the change to `bin/pyang` restores the fix.

```
% git diff ../../../bin/pyang
diff --git a/bin/pyang b/bin/pyang
index 3040858..2b71445 100755
--- a/bin/pyang
+++ b/bin/pyang
@@ -451,8 +451,6 @@ Validates the YANG module in <filename> (or stdin), and all its dependencies."""
             continue
         if (ctx.implicit_errors is False and
             epos.top.arg not in modulenames and
-            hasattr(epos.top, 'i_modulename') and
-            epos.top.i_modulename not in modulenames and
             (not hasattr(epos.top, 'i_modulename') or
              epos.top.i_modulename not in modulenames) and
             epos.ref not in filenames):
```

```
test_i680% pyang --max-line-len=70 -f tree -o mod1.tree mod1.yang -V
# module search path: .:/Users/william/Development/pyang/feature/modules:/Users/william/yang/modules:/System/Library/Frameworks/Python.framework/Versions/2.7/share/yang/modules
# read mod1.yang (CL)
# read mod2.yang
# READ mod2@2020-10-06.yang
```

Commit e929e19 shows the above.

**Comment by wlupton** [comment]
Reverting the change to `pyang/repository.py` doesn't affect the fix (but note that `mod2` is now only parsed once).

```
% git diff
diff --git a/pyang/repository.py b/pyang/repository.py
index e6d7c9b..e344562 100644
--- a/pyang/repository.py
+++ b/pyang/repository.py
@@ -112,7 +112,7 @@ class FileRepository(Repository):
         self.modules = []
         def add_files_from_dir(d):
             try:
-                files = reversed(sorted(os.listdir(d)))
+                files = os.listdir(d)
             except OSError:
                 files = []
             for fname in files:
```

```
test_i680% pyang --max-line-len=70 -f tree -o mod1.tree mod1.yang -V
# module search path: .:/Users/william/Development/pyang/feature/modules:/Users/william/yang/modules:/System/Library/Frameworks/Python.framework/Versions/2.7/share/yang/modules
# read mod1.yang (CL)
# read mod2.yang
```

Commit c59f480 shows the above.

**Comment by wlupton** [comment]
In summary, I think that the simple `bin/pyang` fix will address the original problem, but some other changes might be called for.

Please let me know if you'd like me to collapse all the changes into a single commit.

**Comment by mbj4668** [comment]
This looks good; please squash into one commit.

**Comment by wlupton** [comment]
Thanks. Done.

**Pull request merged**
