### PR TITLE
Report when reading YANG files when --verbose

### PR DESCRIPTION
**Pull request by wlupton**
The output is to stderr and looks like this ("CL" means "command line"):
```
% pyang --verbose --path ... bbf-l2-forwarding.yang 
# read bbf-l2-forwarding.yang (CL)
# read bbf-l2-forwarding-base.yang
# read bbf-l2-forwarding-flooding-policies.yang
# read ../types/bbf-yang-types.yang
# read ../interfaces/bbf-interface-usage.yang
# read /Users/william/Applications/yang/standard/ietf/RFC/ietf-interfaces.yang
# read /Users/william/Applications/yang/standard/ietf/RFC/ietf-yang-types.yang
# read /Users/william/Applications/yang/standard/ietf/RFC/iana-if-type.yang
# read ../types/bbf-if-type.yang
# read ../sub-interfaces/bbf-frame-classification.yang
# read ../types/bbf-dot1q-types.yang
# read ../types/bbf-inet-types.yang
# read bbf-l2-forwarding-forwarders.yang
# read bbf-l2-forwarding-forwarding-databases.yang
# read bbf-l2-forwarding-mac-learning.yang
# read bbf-l2-forwarding-split-horizon-profiles.yang
# read bbf-l2-forwarding-mac-learning-control.yang
```

### CODE REVIEW

**Comment by wlupton** [comment]
I should also have mentioned that if a file is reported as "READ" (upper-case) rather then "read" then the actual file (the "real file") has already been read. This sometimes seems to happen, possibly when files exist in multiple places on the search path?

**Comment by mbj4668** [comment]
thanks, seems useful!

**Comment by glennmatthews** [comment]
I wish this could have been implemented in a backwards-compatible way somehow - changing the API signature for `get_module_from_handle()` like this has broken code we have that both implements and calls this API.

**Comment by mbj4668** [comment]
Hmm, I guess I missed that.  I think I didn't review the code carefully enough.
What if we reverted the change to the signature, and instead added 'verbose' as a property to the Repository class, default false.  Then add a method in Repository to set the flag.

**Comment by wlupton** [comment]
Speaking as the original contributor: sorry!

**Comment by glennmatthews** [comment]
Thanks for the speedy response, and no worries - these things happen! @mbj4668 I think that sounds like a very reasonable fix.

**Comment by mbj4668** [comment]
I have craete a branch https://github.com/mbj4668/pyang/tree/fix-verbose-filename-print with a fix where the FileRepository constructor gets (an optional) verbose param.  Please review this fix, and let me know if it solves the issue.  If so, I'll make a new release.  (next time I'll remember to update the minor vsn number so that we can use the patch number for things like this...)

**Comment by glennmatthews** [comment]
Appears to work effectively - thanks!

**Pull request merged**
