### PR TITLE
fix bash completion script

### PR DESCRIPTION
**Pull request by rski**
have is deprecated and not available in certain systems,
use _have, the recommended function instead

### CODE REVIEW

**Comment by fredgan** [comment]
@rski Hi Romanos, Can you give some links about from which version `have` is deprecated?

**Comment by rski** [comment]
comited 2011 it seems: https://github.com/scop/bash-completion/commit/20c05b43b6e44be8ae3c5025a77eca62a48c5a62 and it's included in v1.90, which was released in 2011 too

**Comment by rski** [comment]
> @rski Hi Romanos, Can you give some links about from which version `have` is deprecated?

Hi fredgan, gentle ping

**Comment by fredgan** [comment]
I think it's OK.

**Pull request merged**
