### PR TITLE
Improve YANG parsing for xPaths (when, must) substatements

### PR DESCRIPTION
**Pull request by yang-catalog**
Signed-off-by: miroslav.kovac <miroslav.kovac@pantheon.tech>

### CODE REVIEW

**Comment by mbj4668** [comment]
This looks very useful.  Could you also add test cases that demonstrate / test  these new capabilities?

**Comment by yang-catalog** [comment]
hi, @mbj4668  could you please let me know what kind of error is that in the travis? I have no idea how to fix that. thank you in advance.

Miroslav K.

**Comment by mbj4668** [comment]
It checks that the test doesn't leave any temporary files behind, I think.

$ git ls-files . --exclude-standard --others | tee "$TMP"
test/test_xpath/temp.txt

BTW. in all error strings etc, "xpath" should be spelled "XPath".  That's
the official name.  No "Xpath", "XPATH" or "xPath".

Den tis 11 sep. 2018 kl 16:15 skrev yang-catalog <notifications@github.com>:

**Comment by yang-catalog** [comment]
Ok got it thx

**Comment by mbj4668** [comment]
I just realized that you treat a missing node as a XPATH_SYNTAX_ERROR.  This is unfortunate, and not really correct.  It is strictly speaking not an error to refer to a non-existing node.  It would be best to define a new error, perhaps XPATH_MISSING_NODE for these.  By default, XPATH_MISSING_NODE should be a warning, not an error.  By separating these thing in our code, we give the user more flexibility.

**Comment by yang-catalog** [comment]
> I just realized that you treat a missing node as a XPATH_SYNTAX_ERROR. This is unfortunate, and not really correct. It is strictly speaking not an error to refer to a non-existing node. It would be best to define a new error, perhaps XPATH_MISSING_NODE for these. By default, XPATH_MISSING_NODE should be a warning, not an error. By separating these thing in our code, we give the user more flexibility.

Done

**Comment by mbj4668** [comment]
After merging, I fixed the code to align with the 80 characters line length convention, and cleaned the test case a bit.

But I'm not happy about the XPATH_MISSING_NODE text; it used to say:
ietf-netconf-notifications@2012-02-06.yang:286: warning: XPath node ../confirm-event != 'timeout' is missing

it now says:

ietf-netconf-notifications@2012-02-06.yang:286: warning: XPath for "../confirm-event != 'timeout'" does not exist

which is also not good.  it should say:
The node ../confirm-event is nout found

or soemthinh similar.  Is this something you can look at?

**Pull request merged**
