### PR TITLE
Emit module name (instead of prefix) for augmented nodes when using tree format

### PR DESCRIPTION
**Pull request by markafarrell**
This will assist with determining the naming required for inputs to json2xml.

Addresses #419

### CODE REVIEW

**Comment by markafarrell** [comment]
re-open to re-run ci

**Comment by mbj4668** [comment]
Note that the tree diagram syntax with prefix is defined in RFC 8340.
That said, printing the module might also be nice.  However, it should be requested with a parameter -tree-module-name-prefix for example.  Also please add a test case for this new feature.

**Comment by markafarrell** [comment]
--tree-module-name-prefix switch added to enable the substitution of prefixes with module names for tree output.
Tests also added.

**Comment by mbj4668** [comment]
One last thing, can you also update the docs with this new parameter; specifically doc/pyang.1.dbk.

You can ignore the travis build failure for python 3.5.

**Comment by markafarrell** [comment]
Updated to also translate prefixes of types. 
Added documentation to doc/pyang.1.dbk
Also updated etc/bash_completion.d/pyang to include new switches (and some old ones that were missing)

**Pull request merged**
