### PR TITLE
Update plugin.py

### PR DESCRIPTION
**Pull request by ankitjain093**
Add exception handle for AttributeError in case plugin does not have name attribute

### CODE REVIEW

**Comment by vnitinv** [comment]
@mbj4668 Martin, What if someone introduces a plugin named` abc` with `name` attribute but I am a user of `xyz` plugin. `xyz` will get `False` from the given function. 

It will be almost impossible to figure out that the main culprit is other plugin as there is no logging message or exception. At least we should be logging error that `abc` plugin threw `AttirbuteError`.

**Comment by mbj4668** [comment]
Hmm, I think I merged this too quickly.  All plugins will have a name attribute; it is initialized in Plugin.__init__.   So @ankitjain093 , did you have a use case where this was a problem?

@vnitinv, I don't understand what you mean with the abc / xyz example.

**Comment by vnitinv** [comment]
@mbj4668 Martin, I just tried abc and xyz as a reference example for plugins. I think this merge should be either reverted back or add error log before returning False in exception.

**Comment by mbj4668** [comment]
Reverted in 458a50fcdcab203142797b831bbd338c5c3c681c.

**Pull request merged**
